project_id = "mbogadvtjkoxajbtpcyz"

[functions.initialize-subscription]
verify_jwt = false

[functions.fetch-paystack-analytics]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.list-banks]
verify_jwt = false

[functions.resolve-bank-account]
verify_jwt = false

[functions.retry-failed-payments]
verify_jwt = false

[functions.manage-staff]
verify_jwt = true

[functions.analytics-ai-insights]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-reset-password]
verify_jwt = false

[functions.initialize-one-time-payment]
verify_jwt = false

[functions.superadmin]
verify_jwt = false

[functions.verify-transaction]
verify_jwt = false

[functions.verify-one-time-payment]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
